cluster.name: stanlee-de-es
node.name: ${HOSTNAME}
node.attr.rack: r2
node.master: false
node.data: true
thread_pool.write.queue_size: 50000
node.max_local_storage_nodes: 4
discovery.zen.fd.ping_interval: 30s
discovery.zen.fd.ping_retries: 6
discovery.zen.fd.ping_timeout: 120s
indices.memory.index_buffer_size: 20%
transport.tcp.compress: true
http.compression: true
indices.queries.cache.size: 30%
cluster.routing.allocation.same_shard.host: true
path.data: /data/es/data
bootstrap.memory_lock: true
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["10.1.144.48","10.1.144.49","10.1.144.47"]
discovery.zen.minimum_master_nodes: 2
gateway.recover_after_nodes: 1
xpack.security.enabled: false
bootstrap.system_call_filter: false
reindex.remote.whitelist: "*.*.*.*:*"
transport.tcp.port: 9301-9400
